apiVersion: v2
name: sd-limit-and-exposure-management
description: "BIAN Service Domain: Limit And Exposure Management (Manage pattern, Risk and Compliance)"
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - bian
  - manage
annotations:
  bian/business-area: "Risk and Compliance"
  bian/business-domain: "Credit Risk"
  bian/asset-type: "Exposure Limit"
  bian/control-record: "Exposure Limit Management Plan"
